AWSTemplateFormatVersion: '2010-09-09'
Description:  Base SG to assign DB instances to allow access from Datamover instance
Resources:
  BaseDataMover:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Vernova-DataMover-SG
      GroupDescription: Base SG to assign DB instances to allow access from Datamover instance
      VpcId: !ImportValue vpcid
      Tags:
        - Key: Name
          Value: Vernova-DataMover-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 5432
          SourcePrefixListId: !ImportValue Vernova-DataMover-Prefix-List
        
Outputs:
  DataMoverSg:
    Description: Base SG to assign to datamover
    Value: !Ref BaseDataMover
    Export:
      Name: Vernova-DataMover-SG