---
AWSTemplateFormatVersion: "2010-09-09"
Description: IP set for Imperva WAF - used for CloudFront resources
Resources:
  CFIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses: 
        - "199.83.128.0/21"
        - "198.143.32.0/19"
        - "149.126.72.0/21"
        - "103.28.248.0/22"
        - "45.64.64.0/22"
        - "185.11.124.0/22"
        - "192.230.64.0/18"
        - "107.154.0.0/16"
        - "45.60.0.0/16"
        - "45.223.0.0/16"
        - "131.125.128.0/17"
      Description: "IPs used by Imperva WAF"
      IPAddressVersion: "IPV4"
      Name: "Imperva-WAF-CLOUDFRONT"
      Scope: CLOUDFRONT

Outputs:
  ExportCFIPSet:
    Value: !GetAtt CFIPSet.Arn
    Export:
      Name: "CloudFrontWAFIPSet"