AWSTemplateFormatVersion: "2010-09-09"
Description: Create Backup plans and rules
Resources:
  NonProdBackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: Vernova-Non-Prod-Backup-Plan
        BackupPlanRule:
          - RuleName: Vernova-Non-Prod-Rule
            EnableContinuousBackup: True
            TargetBackupVault: !ImportValue Vernova-Non-Prod-Vault-Name
            RecoveryPointTags:
              Vault: non-prod
            ScheduleExpression: cron(0 4 * * ? *)
            Lifecycle:
              DeleteAfterDays: 14
            CompletionWindowMinutes: 1440
            StartWindowMinutes: 120

  
  NonProdBackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref NonProdBackupPlan
      BackupSelection:
        SelectionName: Vernova-Non-Prod-Backup-Selection
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/bot/vn-backup-service" 
        NotResources:
          - "arn:aws:backup-gateway:*:*:vm/*"
          - "arn:aws:ec2:*:*:instance/*"
          - "arn:*:fsx:*"
          - "arn:aws:rds:*:*:cluster:*"
          - "arn:aws:s3:::*"
          - "arn:aws:storagegateway:*:*:gateway/*"
        ListOfTags:
          - ConditionKey: env
            ConditionType: STRINGEQUALS
            ConditionValue: dev
          - ConditionKey: env
            ConditionType: STRINGEQUALS
            ConditionValue: qa
          - ConditionKey: env
            ConditionType: STRINGEQUALS
            ConditionValue: stg
          
  ProdBackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: Vernova-Prod-Backup-Plan
        BackupPlanRule:
          - RuleName: Vernova-Prod-Rule
            EnableContinuousBackup: True
            TargetBackupVault: !ImportValue Vernova-Prod-Vault-Name
            RecoveryPointTags:
              Vault: prod
            ScheduleExpression: cron(0 4 * * ? *)
            Lifecycle:
              DeleteAfterDays: 35
            CompletionWindowMinutes: 1440
            StartWindowMinutes: 120

  
  ProdBackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref ProdBackupPlan
      BackupSelection:
        SelectionName: Vernova-Prod-Backup-Selection
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/bot/vn-backup-service" 
        NotResources:
          - "arn:aws:backup-gateway:*:*:vm/*"
          - "arn:aws:ec2:*:*:instance/*"
          - "arn:*:fsx:*"
          - "arn:aws:rds:*:*:cluster:*"
          - "arn:aws:s3:::*"
          - "arn:aws:storagegateway:*:*:gateway/*"
        ListOfTags:
          - ConditionKey: env
            ConditionType: STRINGEQUALS
            ConditionValue: prd
          - ConditionKey: env
            ConditionType: STRINGEQUALS
            ConditionValue: prod
        # Conditions:
        #   - StringNotEquals:
        #       ConditionKey: aws:ResourceTag/ ## Tag key of rubrik resources
        #       ConditonValue: ## Tag value for rubrik resources
