---
AWSTemplateFormatVersion: '2010-09-09'
Description: Export of GR created resources accounts.
# Created by s.border 
# export resources provisioned though the GR build process
# so they can be imported into subsequent stack runs.
# History : 
  # 03-10: added exports on subnets for app , igr and db
Parameters:
  VpcID:
    Description: specify the vpc id that was provisioned in guard rails.
    Type: String

  AZ1Name:
    Description: AZ1 Name
    Type: String

  AZ2Name:
    Description: AZ2 Name
    Type: String

  AZ1ID:
    Description: AZ1 Use ID
    Type: String
   
  AZ2ID:
    Description: AZ2 Use ID
    Type: String

  VPCCidr:
    Description: VPC CIDR 
    Type: String
    
  VPCName:
    Description: VPC Name
    Type: String
    
  VPCAlias:
    Description: VPC Alias Name
    Type: String
   
  SubnetFirewall:
    Description: Firewall Subnet ID
    Type: String
    
  SubnetNAT:
    Description: Init build NAT subnet Id
    Type: String

  VPCResolverSG:
    Description: SG for DNS Resolver
    Type: String
  
  InternetRouteTableID:
    Description: Internet route table Id
    Type: String

  FirewallVPCEndpointID:
    Description: Firewall VPC Endpoint ID
    Type: String
  
  PrivateRouteTableID:
    Description: Private route table Id
    Type: String
  
  VernovaBastionPrefixList:
    Description: Vernova-Bastion-Prefix-List ID
    Type: String
  
  VernovaDataMoverPrefixList:
    Description: Vernova-DataMover-Prefix-List ID
    Type: String
  
  VernovaImpervaPrefixList:
    Description: Vernova-Imperva-Prefix-List ID
    Type: String
  
  VernovaLDAPPrefixList:
    Description: Vernova-LDAP-Prefix-List ID
    Type: String
  
  VernovaSMTPPrefixList:
    Description: Vernova-SMTP-Prefix-List ID
    Type: String
  
  BusinessName:
    Description: BusinessName
    Type: String
  
  VernovaDomainJoinUSPrefixList:
    Description: Vernova-Domain-Join-US-Prefix-List ID
    Type: String
  
  
Conditions:
  HasNot: !Equals [ 'true', 'false' ]
 
# dummy (null) resource, never created
Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot

Outputs:
  ExportVPCID:
    Value: !Ref VpcID
    Export:
      Name: "vpcid"
  
  ExportVPCAlias:
    Value: !Ref VPCAlias
    Export:
      Name: "VPCAlias"

  ExportAZ1Name:
    Value: !Ref AZ1Name
    Export:
      Name: "AZ1Name"

  ExportAZ2Name:
    Value: !Ref AZ2Name
    Export:
      Name: "AZ2Name"

  ExportVPCCIDR:
    Value: !Ref VPCCidr
    Export:
      Name: "VPCCidr"  

  ExportVPCName:
    Value: !Ref VPCName
    Export:
      Name: "VPCName"
      
  ExportSnInternetAZ1:
    Value: !Ref SubnetFirewall
    Export:
      Name: "SnInternetAZ1"
      
  ExportSnNATAZ1:
    Value: !Ref SubnetNAT
    Export:
      Name: "SnNATAZ1"
  
  ExportAZ1ID:
    Value: !Ref AZ1ID
    Export:
      Name: "AZ1ID"  
  
  ExportAZ2ID:
    Value: !Ref AZ2ID
    Export:
      Name: "AZ2ID"  
  
  ExportDNSResolver:
    Value: !Ref "VPCResolverSG"
    Export: 
      Name: "VPCResolverSG"

  ExportInternetRouteTableId:
    Value: !Ref "InternetRouteTableID"
    Export: 
      Name: "rt-InternetId"

  ExportFirewallVPCEndpointId:
    Value: !Ref "FirewallVPCEndpointID"
    Export:
      Name: "FirewallVPCEndpointID"
  
  ExportPrivateRouteTableId:
    Value: !Ref "PrivateRouteTableID"
    Export: 
      Name: "rt-PrivateId"

  ExportBastionPL:
    Value: !Ref "VernovaBastionPrefixList"
    Export: 
      Name: "Vernova-Bastion-Prefix-List"
  
  ExportDataMoverPL:
    Value: !Ref "VernovaDataMoverPrefixList"
    Export: 
      Name: "Vernova-DataMover-Prefix-List"
  
  ExportImpervaPL:
    Value: !Ref "VernovaImpervaPrefixList"
    Export: 
      Name: "Vernova-Imperva-Prefix-List"
  
  ExportLDAPPL:
    Value: !Ref "VernovaLDAPPrefixList"
    Export: 
      Name: "Vernova-LDAP-Prefix-List"
  
  ExportSMTPPL:
    Value: !Ref "VernovaSMTPPrefixList"
    Export: 
      Name: "Vernova-SMTP-Prefix-List"

  ExportUSDJPL:
    Value: !Ref "VernovaDomainJoinUSPrefixList"
    Export: 
      Name: "Vernova-Domain-Join-US-Prefix-List"
  
  
  ExportBusinessName:
    Value: !Ref "BusinessName"
    Export: 
      Name: "business-name"