---
AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates the cluster & instance parameter groups that are neccessary for builds of RDS Aurora MySQL instances.

Parameters:
  uai:
    Type: String
    Description: The uai of the application being charged for usage.
    ConstraintDescription: The uai must be valid, but specified as 'uai' in upper case followed by 7 digits
    AllowedPattern: '^(uai|uai)[0-9]*$'
    MinLength: 10
    MaxLength: 10
    Default: 'uai3064620'

Resources:
  rdsauroramysqlnonprodparamgroup80:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: mysql default parameter group with slow query log enabled and Event scheduler enabled 
      Family: 'aurora-mysql8.0'
      DBParameterGroupName: 'gev-dba-rds-para-group-non-prod-aurora-mysql-80'
      Parameters:
        slow_query_log: "1"
        max_connect_errors: "9999"
        wait_timeout: "3600"
        interactive_timeout: "3600"
        max_allowed_packet: "33554432"
      Tags: 
        - Key: Name
          Value: 'gev-dba-rds-para-group-non-prod-aurora-mysql-80'
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdsauroramysqlprodparamgroup80:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: mysql prod parameter group with slow query log enabled and Event scheduler enabled 
      DBParameterGroupName: 'gev-dba-rds-para-group-prod-aurora-mysql-80'
      Family: 'aurora-mysql8.0'
      Parameters:
        slow_query_log: "1"
        max_connect_errors: "9999"
        wait_timeout: "3600"
        interactive_timeout: "3600"
        max_allowed_packet: "33554432"
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdsprodauroramysqlclusterparamgroup80:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: Aurora MySQL Cluster Parameter Group for 8.0 with event_scheduler on and auditing on
      Family: 'aurora-mysql8.0'
      DBClusterParameterGroupName: "gev-dba-cluster-para-group-prod-mysql-8"
      Parameters:
        event_scheduler: "ON"
        server_audit_logging: "1"
        server_audit_events: "CONNECT,QUERY,TABLE"
        server_audit_excl_users: "admin"
        require_secure_transport: 'ON'
      Tags:
        - Key: "created_by"
          Value: "gev-dba"
        - Key: "support-group"
          Value: "dig-tech-cts-cloud-db-support-team"
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdsnonprodauroramysqlclusterparamgroup80:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: Aurora MySQL Cluster Parameter Group for 8.0 without server audit
      Family: 'aurora-mysql8.0'
      DBClusterParameterGroupName: "gev-dba-cluster-para-group-non-prod-mysql-8"
      Parameters:
        event_scheduler: "ON"
        server_audit_logging: "0"
        require_secure_transport: 'ON'
      Tags:
        - Key: "created_by"
          Value: "gev-dba"
        - Key: "support-group"
          Value: "dig-tech-cts-cloud-db-support-team"
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

Outputs:
  rdsauroramysqlnonprodparamgroup80:
    Description: "mysql default parameter group with slow query log enabled and Event scheduler enabled "
    Value: !Ref rdsauroramysqlnonprodparamgroup80
    Export:
      Name: 'gev-dba:rds:parametergroups:aurora-mysql:non-prod:80'
      
  rdsauroramysqlprodparamgroup80:
    Description: "mysql ISO parameter group with slow query log enabled and Event scheduler enabled "
    Value: !Ref rdsauroramysqlprodparamgroup80
    Export:
      Name: 'gev-dba:rds:parametergroups:aurora-mysql:prod:80'

  rdsprodauroramysqlclusterparamgroup80:
    Description: "RDS Cluster Parameter Group with Prod parameters for MySQL 8 "
    Value: !Ref rdsprodauroramysqlclusterparamgroup80
    Export:
      Name: 'gev-dba:rds:parametergroups:aurora-mysql-cluster:prod:8'
  
  rdsnonprodauroramysqlclusterparamgroup80:
    Description: "RDS Cluster Parameter Group with Non-prod parameters for MySQL 8 "
    Value: !Ref rdsnonprodauroramysqlclusterparamgroup80
    Export:
      Name: 'gev-dba:rds:parametergroups:aurora-mysql-cluster:non-prod:8'
  
