AWSTemplateFormatVersion: "2010-09-09"
Description: Create SNS topic for aws backup failure notifications
Resources:
  AWSBackupFailureNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: "vernova-aws-backup-failure-notifications@ge.com"
      Protocol: email
      FilterPolicy:
        State:
          - "FAILED"
          - "EXPIRED"
      TopicArn: !Ref AWSBackupFailureNotificationTopic

  AWSBackupFailureNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'Vernova-OPS-AWS-Backup-Failure-Notifications'
  
  AWSBackupFailureNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref AWSBackupFailureNotificationTopic
      PolicyDocument:
        Version: 2008-10-17
        Id: __default_policy_ID
        Statement:
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
              - SNS:GetDataProtectionPolicy
            Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:Vernova-OPS-AWS-Backup-Failure-Notifications
            Condition:
              StringEquals:
                AWS:SourceOwner: !Sub "${AWS::AccountId}"
          - Sid: AllowBackupService
            Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action: SNS:Publish
            Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:Vernova-OPS-AWS-Backup-Failure-Notifications

Outputs:
  BackupFailureSNSTopic:
    Description: SNS topic to inform Cloud Ops about AWS Backup failure notifications
    Value: !Ref AWSBackupFailureNotificationTopic
    Export:
      Name: Vernova-Backup-Failure-SNS-Topic