AWSTemplateFormatVersion: "2010-09-09"
Description: Create 2 backup vaults
Resources:
  NonProdBackupVault:
    Type: AWS::Backup::BackupVault
    Properties: 
      AccessPolicy: 
        Version: 2012-10-17
        Statement:
          - Sid: CloudTeamAccessOnly
            Effect: Deny
            Principal: "*"
            Action:
              - backup:DeleteBackupVault
              - backup:PutBackupVaultAccessPolicy
              - backup:DeleteBackupVaultAccessPolicy
              - backup:GetBackupVaultAccessPolicy
              - backup:StartBackupJob
              - backup:StartCopyJob
              - backup:StartRestoreJob
              - backup:GetBackupVaultNotifications
              - backup:PutBackupVaultNotifications
              - backup:DeleteBackupVaultNotifications
            Resource: "*"
            Condition:
              ArnNotEquals:
                aws:PrincipalArn:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/p/vnadmin"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/p/engineer"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn-build-admin"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/p/support"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/bot/vn-lz-deploy-resources"
      BackupVaultName: Vernova-Non-Prod-Backup-Vault
      BackupVaultTags: 
        env : dev
      Notifications:
        BackupVaultEvents:
          - BACKUP_JOB_COMPLETED
          - COPY_JOB_FAILED
          - RESTORE_JOB_COMPLETED
          - COPY_JOB_FAILED
          - RECOVERY_POINT_MODIFIED
          - S3_BACKUP_OBJECT_FAILED
          - S3_RESTORE_OBJECT_FAILED
        SNSTopicArn: !ImportValue Vernova-Backup-Failure-SNS-Topic

  ProdBackupVault:
    Type: AWS::Backup::BackupVault
    Properties: 
      AccessPolicy: 
        Version: 2012-10-17
        Statement:
          - Sid: CloudTeamAccessOnly
            Effect: Deny
            Principal: "*"
            Action:
              - backup:DeleteBackupVault
              - backup:PutBackupVaultAccessPolicy
              - backup:DeleteBackupVaultAccessPolicy
              - backup:GetBackupVaultAccessPolicy
              - backup:StartBackupJob
              - backup:StartCopyJob
              - backup:StartRestoreJob
              - backup:GetBackupVaultNotifications
              - backup:PutBackupVaultNotifications
              - backup:DeleteBackupVaultNotifications
            Resource: "*"
            Condition:
              ArnNotEquals:
                aws:PrincipalArn:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/p/vnadmin"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/p/engineer"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn-build-admin"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/p/support"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/vn/bot/vn-lz-deploy-resources"
      BackupVaultName: Vernova-Prod-Backup-Vault
      BackupVaultTags: 
        env : prod
      Notifications:
        BackupVaultEvents:
          - BACKUP_JOB_COMPLETED
          - COPY_JOB_FAILED
          - RESTORE_JOB_COMPLETED
          - COPY_JOB_FAILED
          - RECOVERY_POINT_MODIFIED
          - S3_BACKUP_OBJECT_FAILED
          - S3_RESTORE_OBJECT_FAILED
        SNSTopicArn: !ImportValue Vernova-Backup-Failure-SNS-Topic

Outputs:
  NonProdVaultExport:
    Description: Vernova-Non-Prod vault name
    Value: !Ref NonProdBackupVault
    Export:
      Name: Vernova-Non-Prod-Vault-Name
  ProdVaultExport:
    Description: Vernova-Non-Prod vault name
    Value: !Ref ProdBackupVault
    Export:
      Name: Vernova-Prod-Vault-Name
