---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create a common basic ALB
Parameters:
  UAI:
    Type: String
    Description: The UAI of the application being managed.
    ConstraintDescription: The uai must be valid, but specified as 'uai' in lower case followed by 7 digits
    AllowedPattern: '^uai[0-9]{7}$'

  AppName:
    Type: String
    Description: Name of the application

  Env:
    Type: String
    Description: Environment of the application
    AllowedValues: [ 'dev', 'qa', 'prd', 'lab', 'stg', 'dr' ]
  SecurityGroupValue:
    Type: String
    Description: SG that was created
  TimeoutToUse:
    Type: String
    Description: Timeout to use for idle timeout
    Default: 60
  BucketPath:
    Type: String
    Description: Prefix for the bucket path for storing logs in the application related path

Resources:
  InternalApplicationLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: 'ipv4'
      Scheme: internal
      Name: !Sub app-${UAI}-${AppName}-${Env}-int
      Subnets:
        - !ImportValue internal-app-az1
        - !ImportValue internal-app-az2
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: !Ref TimeoutToUse
        #- Key: access_logs.s3.enabled
        #  Value: true
        #- Key: access_logs.s3.bucket
        #  Value: vn-lz-common-log-bucket-for-alb
        #- Key: access_logs.s3.prefix
        #  Value: !Ref BucketPath
      SecurityGroups:
        - !Ref SecurityGroupValue
      Type: application
      Tags:
        - Key: uai
          Value: !Ref UAI
        - Key: AppName
          Value: !Ref AppName
        - Key: env
          Value: !Ref Env
        - Key: Stack_ID
          Value: !Sub ${AWS::StackId}
        - Key: Stack_Name
          Value: !Sub ${AWS::StackName}