AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates the parameters groups that are neccessary Postgres RDS instance builds.
              It must be created prior to any RDS Instances
              Last version 30-may-2020

Parameters:
  uai:
    Type: String
    Description: The uai of the application being charged for usage.
    ConstraintDescription: The uai must be valid, but specified as 'uai' in upper case followed by 7 digits
    AllowedPattern: '^(uai|uai)[0-9]*$'
    MinLength: 10
    MaxLength: 10
    Default: 'uai3064620'

Resources:
  rdspsqlprdparamgroup13:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 13 prod parameter group with audit enabled
      Family: 'postgres13'
      DBParameterGroupName: 'gev-dba-parameter-group-prod-postgre-13'
      Parameters:
        rds.log_retention_period: "10080"  # 7 days
        rds.force_ssl: 1                   # On
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_connections: "1"
        log_disconnections: "1"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlnonprdparamgroup13:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 13 non-prod parameter group with audit enabled
      Family: 'postgres13'
      DBParameterGroupName: 'gev-dba-parameter-group-non-prod-postgre-13'
      Parameters:
        rds.force_ssl: 1
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlprdparamgroup14:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 14 prod parameter group with audit enabled
      Family: 'postgres14'
      DBParameterGroupName: 'gev-dba-parameter-group-prod-postgre-14'
      Parameters:
        rds.log_retention_period: "10080"  # 7 days
        rds.force_ssl: 1                   # On
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_connections: "1"
        log_disconnections: "1"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlnonprdparamgroup14:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 14 non-prod parameter group with audit enabled
      Family: 'postgres14'
      DBParameterGroupName: 'gev-dba-parameter-group-non-prod-postgre-14'
      Parameters:
        rds.force_ssl: 1
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlprdparamgroup15:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 15 prod parameter group with audit enabled
      Family: 'postgres15'
      DBParameterGroupName: 'gev-dba-parameter-group-prod-postgre-15'
      Parameters:
        rds.log_retention_period: "10080"  # 7 days
        rds.force_ssl: 1                   # On
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_connections: "1"
        log_disconnections: "1"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlnonprdparamgroup15:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 15 non-prod parameter group with audit enabled
      Family: 'postgres15'
      DBParameterGroupName: 'gev-dba-parameter-group-non-prod-postgre-15'
      Parameters:
        rds.force_ssl: 1
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlprdparamgroup16:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 16 prod parameter group with audit enabled
      Family: 'postgres16'
      DBParameterGroupName: 'gev-dba-parameter-group-prod-postgre-16'
      Parameters:
        rds.log_retention_period: "10080"  # 7 days
        rds.force_ssl: 1                   # On
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_connections: "1"
        log_disconnections: "1"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'

  rdspsqlnonprdparamgroup16:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: postgresql 16 non-prod parameter group with audit enabled
      Family: 'postgres16'
      DBParameterGroupName: 'gev-dba-parameter-group-non-prod-postgre-16'
      Parameters:
        rds.force_ssl: 1
        rds.restrict_password_commands: 1
        pgaudit.role: "rds_pgaudit"
        shared_preload_libraries: "pgaudit,pg_stat_statements,pglogical"
        pgaudit.log: "ddl"
        log_rotation_size: "25600"
        log_hostname: 1
      Tags: 
        - Key: 'env'
          Value: 'prd'
        - Key: 'uai'
          Value: !Sub '${uai}'
        - Key: 'support-group'
          Value: 'dig-tech-cts-cloud-db-support-team'
        - Key: 'created'
          Value: 'gev-dba'
        - Key: 'Stack name'
          Value: !Sub '${AWS::StackName}'


Outputs:

  rdspsqlprdparamgroup13:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 13"
    Value: !Ref rdspsqlprdparamgroup13
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:prod:13'
    
  rdspsqlnonprdparamgroup13:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 13"
    Value: !Ref rdspsqlnonprdparamgroup13
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:non-prod:13'

  rdspsqlprdparamgroup14:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 14"
    Value: !Ref rdspsqlprdparamgroup14
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:prod:14'
  
  rdspsqlnonprdparamgroup14:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 14"
    Value: !Ref rdspsqlnonprdparamgroup14
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:non-prod:14'

  rdspsqlprdparamgroup15:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 15"
    Value: !Ref rdspsqlprdparamgroup15
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:prod:15'
  
  rdspsqlnonprdparamgroup15:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 15"
    Value: !Ref rdspsqlnonprdparamgroup15
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:non-prod:15'

  rdspsqlprdparamgroup16:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 16"
    Value: !Ref rdspsqlprdparamgroup16
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:prod:16'
    
  rdspsqlnonprdparamgroup16:
    Description: "RDS Parameter Group that Prod parameters with audit enabled for PostgreSQL 16"
    Value: !Ref rdspsqlnonprdparamgroup16
    Export:
      Name: !Sub 'gev-dba:rds:parametergroups:postgres:non-prod:16'
