AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create kinesis Firehose

Parameters:
  UAI:
    Type: String
    Description: The UAI of the application being managed.
    ConstraintDescription: The uai must be valid, but specified as 'uai' in lower case followed by 7 digits
    AllowedPattern: '^uai[0-9]{7}$'

  AppName:
    Type: String
    Description: 'Which instance of the application. Example: app1. Must be lowercase. Max 15 chars.'
    AllowedPattern: ^[a-z][a-z0-9\._\-]*[a-z0-9]$
    ConstraintDescription: Must contain only lower case letters, digits or -. Min 3 chars. Max 15. Must start with a letter and end with a letter or digit
    MinLength: !!int 3
    MaxLength: !!int 15

  Env:
    Type: String
    Description: Env instance of the resource.
    Default: dev
    AllowedValues: [ 'dev', 'qa', 'prd', 'lab', 'stg', 'dr' ]

  DeliveryStreamName:
    Type: String
    Description: The name to use for the service Kinesis Firehose

  KinesisStreamARN:
    Type: String
    Description: The ARN of the Kinesis Data Stream 

  KinesisStreamRoleArn:
    Type: String
    Description: The Role ARN for Kinesis Data Stream 	


  BucketARN:
    Type: String
    Description: ARN of the Destination S3 Bucket

  RoleARN:
    Type: String
    Description: ARN of the IAM Role

  CompressionFormat:
      Type: String
      Description: Compression Format to use for data in destination bucket
      Default: UNCOMPRESSED
      AllowedValues:
      - GZIP
      - HADOOP_SNAPPY
      - Snappy
      - UNCOMPRESSED
      - ZIP

  KmsKey:
    Type: String
    Description: Kinesis Video Stream uses AWS Key Management Service (KMS) to encrypt your data at rest

  LogStreamName:
    Type: String
    Description: Name of the CloudWatch Logging Stream

  Prefix:
    Type: String
    Description: Prefix


  ProcessorsType:
      Type: String
      Description: Processor Type
      Default: MetadataExtraction
      AllowedValues:
      - AppendDelimiterToRecord
      - Lambda
      - MetadataExtraction
      - RecordDeAggregation

  ProcessorsParameterName:
      Type: String
      Description: Processor Type Name
      Default: MetadataExtractionQuery
      AllowedValues:
      - BufferIntervalInSeconds
      - BufferSizeInMBs
      - Delimiter
      - JsonParsingEngine
      - LambdaArn
      - MetadataExtractionQuery
      - NumberOfRetries
      - RoleArn
      - SubRecordType  

  ProcessorsParameterValue:
      Type: String
      Description: Processor Type Value
      Default: '{YYYY : (.ts/1000) | strftime("%Y"), MM : (.ts/1000)
                | strftime("%m"), DD : (.ts/1000) | strftime("%d"), HH: (.ts/1000)
                | strftime("%H")}'     


Resources:
  Firehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "app-${UAI}-${AppName}-${Env}-${DeliveryStreamName}"
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration: 
        KinesisStreamARN: !Ref KinesisStreamARN
        RoleARN: !Ref KinesisStreamRoleArn
      ExtendedS3DestinationConfiguration:
        BucketARN: !Ref BucketARN
        BufferingHints:
          SizeInMBs: 128
          IntervalInSeconds: 900
        CompressionFormat: UNCOMPRESSED
        ErrorOutputPrefix: table/error/!{firehose:error-output-type}/dt=!{timestamp:yyyy'-'MM'-'dd}/h=!{timestamp:HH}/
        Prefix: !Ref Prefix
        RoleARN: !Ref RoleARN
        DynamicPartitioningConfiguration:
          Enabled: true
          RetryOptions:
            DurationInSeconds: 300
        CloudWatchLoggingOptions: 
          Enabled: true
          LogGroupName: "deliverystream"
          LogStreamName: !Ref LogStreamName
        EncryptionConfiguration:
          KMSEncryptionConfig:
            AWSKMSKeyARN: !Ref KmsKey
        ProcessingConfiguration:
          Enabled: true
          Processors:
          - Type: !Ref ProcessorsType
            Parameters:
            - ParameterName: !Ref ProcessorsParameterName
              ParameterValue: !Ref ProcessorsParameterValue


Outputs:

  StreamARN:
    Description: ARN of Kinesis Firehose
    Value: !GetAtt Firehose.Arn

  StreamName:
    Description: Name of Kinesis Firehose
    Value: !Ref Firehose