---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Secret manager to store secret for application

Parameters:

  UAI:
    Type: String
    Description: The UAI of the application being managed.
    ConstraintDescription: The uai must be valid, but specified as 'uai' in lower case followed by 7 digits
    AllowedPattern: '^uai[0-9]{7}$'

  AppInstance:
    Type: String
    Description: "Which instance of the application. Example: app1-dev. Must be lowercase. Max 17 chars."
    AllowedPattern: '^[a-z][a-z0-9\._\-]*[a-z0-9]$'
    ConstraintDescription: "Must contain only lower case letters, digits, '.', '_' or '-'. Min 3 chars. Max 17. Must start with a letter and end with a letter or digit"
    MinLength: 3
    MaxLength: 17

  AppName:
    Type: String
    MaxLength: 20
    AllowedPattern: "[a-z0-9\\-]*"
    Description: AppName, keep to 15 characters or less.

  Env:
    Type: String
    AllowedValues: [ 'dev', 'qa', 'prd', 'lab', 'stg', 'dr' ]

Resources:

  SecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Secret manager for the storing secrets"
      # KmsKeyId: !Ref KMSKeyAtAppLevel
      Name: !Sub "app-${UAI}/${AppName}/${Env}/${AppInstance}"
      # SecretString: !Sub "AccessKey: ${UserKey} , SecretKey: ${UserKey.SecretAccessKey}"
      Tags:
        - Key: Name
          Value: !Sub "app-${UAI}/${AppName}/${Env}/${AppInstance}"
        - Key: uai
          Value: uai1234567890
        - Key: app
          Value: !Ref AppName
        - Key: env
          Value: !Ref Env
        - Key: Stack_ID
          Value: !Sub ${AWS::StackId}
        - Key: Stack_Name
          Value: !Sub ${AWS::StackName}

Outputs:
  SecretARN:
    Description: Secret ARN
    Value: !Ref  SecretsManager            