##### History

AWSTemplateFormatVersion: '2010-09-09'
Description: CF Template to create NACL entries for AppNacl

Resources:
  AppNacl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
      - Key: Name
        Value: application-nacl
      VpcId: !ImportValue vpcid

####### Inbound Rules ########

  
  #Allow all inbound from 10.x
  Ingress1400:
    Properties:
      CidrBlock: 10.0.0.0/8
      Egress: false
      NetworkAclId:
        Ref: AppNacl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 1400
    Type: AWS::EC2::NetworkAclEntry
  
  #Allow all inbound from 3.x
  Ingress1500:
    Properties:
      CidrBlock: 3.0.0.0/8
      Egress: false
      NetworkAclId:
        Ref: AppNacl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 1500
    Type: AWS::EC2::NetworkAclEntry
  
  #Allow inbound TCP from quad 0 on ephemeral ports
  Ingress1600:
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: AppNacl
      Protocol: 6
      PortRange:
        From: 1024
        To: 65535
      RuleAction: allow
      RuleNumber: 1600
    Type: AWS::EC2::NetworkAclEntry
  
####### Outbound Rules ########

  #Allow all outbound to 10.x
  Egress100:
    Properties:
      CidrBlock: 10.0.0.0/8
      Egress: true
      NetworkAclId:
        Ref: AppNacl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Type: AWS::EC2::NetworkAclEntry
  
  #Allow all outbound to 3.x
  Egress101:
    Properties:
      CidrBlock: 3.0.0.0/8
      Egress: true
      NetworkAclId:
        Ref: AppNacl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 101
    Type: AWS::EC2::NetworkAclEntry
  
  #Allow all outbound to quad 0 for HTTPS 
  Egress102:
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: AppNacl
      Protocol: 6
      PortRange:
        From: 443
        To: 443
      RuleAction: allow
      RuleNumber: 102
    Type: AWS::EC2::NetworkAclEntry
  
  #Allow all outbound to quad 0 for HTTP
  Egress103:
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: AppNacl
      Protocol: 6
      PortRange:
        From: 80
        To: 80
      RuleAction: allow
      RuleNumber: 103
    Type: AWS::EC2::NetworkAclEntry
    
Outputs:
  NaclApplication:
    Description: Export NACL ID of Application Subnet   
    Value: !Ref AppNacl
    Export: 
      Name: internal-app-nacl