AWSTemplateFormatVersion: '2010-09-09'
Description: Base SG for ALB  of externally facing web app
Resources:
  WebImpervaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Vernova-Imperva-SG
      GroupDescription: Base SG for ALB  of externally facing web app
      VpcId: !ImportValue vpcid
      Tags:
        - Key: Name
          Value: Vernova-Imperva-SG
      SecurityGroupIngress:
        # allow  HTTPS only from white-listed IP Addresses (refer - https://docs.imperva.com/bundle/z-kb-articles-km/page/c85245b7.html)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourcePrefixListId: !ImportValue Vernova-Imperva-Prefix-List
        
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourcePrefixListId: !ImportValue Vernova-Imperva-Prefix-List
          
      # disable all outgoing traffic by default. The app specific SG will enable it to the specific destination
      SecurityGroupEgress:
        - CidrIp: 127.0.0.1/32
          IpProtocol: "-1" 
Outputs:
  WebImpervaSG:
    Description: Base SG for ALB  of externally facing web app
    Value: !Ref WebImpervaSG
    Export:
      Name: Vernova-Imperva-SG
        